[workspace]
name = "osmprj"
version = "0.1.0"
description = "OpenStreetMap and PostgreSQL project management tool"
channels = ["gis-forge", "https://prefix.dev/thath", "conda-forge"]
platforms = ["linux-64", "osx-arm64"] #  "osx-64", "win-64"]

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
rust = { features = ["rust"], no-default-feature = true }

[dependencies]
osm2pgsql = ">=2"
osm2pgsql-themepark = "*"
pgosm-themepark = "*"

[feature.rust.dependencies]
rust = ">=1.80"

[feature.rust.tasks]
release = "cargo build --release"

[feature.dev.dependencies]
rust = ">=1.80"
psycopg = ">=3.1"
pytest = ">=7.0"
pytest-timeout = ">=2.1"
pytest-mock = ">=3.15.1,<4"
pytest-sugar = ">=1.1.1,<2"
mypy = ">=1.19.1,<2"
pre-commit = ">=4.5.1,<5"
pylint = ">=4.0.4,<5"
pg-helper = "*"
postgresql = ">=18.0"
postgis = ">=3.6.3,<4"
prek = ">=0.3.11,<0.4"
rattler-build = "*"
ruff = ">=0.15.0,<0.16"
tomli = ">=2.0.1" #; python_version<'3.11'",

[feature.dev.activation]
env = { PATH = "$PIXI_PROJECT_ROOT/target/debug:$PATH", OSMPRJ_THEME_PATH = "$PIXI_PROJECT_ROOT/themes" }

[feature.dev.tasks]
test = "pytest tests"
