blank_issues_enabled: false
contact_links:
  - name: 💡 Discussions & ideas
    url: https://github.com/travishathaway/osmprj/discussions
    about: For open-ended questions, ideas, or anything you'd like to discuss with the community.
