"""Integration tests for `osmprj remove`.

These tests require an ephemeral PostgreSQL cluster (pg_e2e fixture) and the
compiled osmprj binary. They do NOT require a real PBF file or osm2pgsql —
schemas are created directly via psycopg to simulate a post-sync state.

Run with:
    pixi run --environment dev pytest tests/integration/test_remove.py -m "slow and integration" -v

Exclude from the default run with:
    pytest -m "not slow"
"""

import subprocess

try:
    import tomllib
except ImportError:
    import tomli as tomllib

import psycopg
import pytest

pytestmark = [pytest.mark.slow, pytest.mark.integration]

SOURCE_NAME = "testregion"
SCHEMA_NAME = "testregion"


@pytest.fixture(scope="module")
def remove_project(run_cmd, pg_e2e, tmp_path_factory):
    """Module-scoped project with a source added and its schema seeded in the DB.

    The schema is created directly via psycopg (no real PBF sync) so the tests
    are fast and network-free.  Each test that mutates state gets its own
    isolated project via the per-test `isolated_project` fixture below.
    """
    project = tmp_path_factory.mktemp("remove_base")
    run_cmd("init", "--db", pg_e2e, cwd=project)
    run_cmd("add", "--path", "/nonexistent/region.pbf", "--name", SOURCE_NAME, cwd=project)

    # Seed a schema in the DB to simulate a completed sync.
    with psycopg.connect(pg_e2e) as conn:
        conn.autocommit = True
        conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA_NAME}"')

    return {"project": project, "db_url": pg_e2e}


def _schema_exists(db_url: str, schema: str) -> bool:
    with psycopg.connect(db_url) as conn:
        row = conn.execute(
            "SELECT 1 FROM information_schema.schemata WHERE schema_name = %s", (schema,)
        ).fetchone()
    return row is not None


@pytest.fixture
def isolated_project(run_cmd, pg_e2e, tmp_path):
    """Per-test isolated project with a fresh source + seeded schema."""
    run_cmd("init", "--db", pg_e2e, cwd=tmp_path)
    run_cmd("add", "--path", "/nonexistent/region.pbf", "--name", SOURCE_NAME, cwd=tmp_path)

    with psycopg.connect(pg_e2e) as conn:
        conn.autocommit = True
        conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA_NAME}"')

    yield {"project": tmp_path, "db_url": pg_e2e}

    # Best-effort cleanup so schemas don't leak between test runs.
    with psycopg.connect(pg_e2e) as conn:
        conn.autocommit = True
        conn.execute(f'DROP SCHEMA IF EXISTS "{SCHEMA_NAME}" CASCADE')


@pytest.fixture
def geofabrik_project(run_cmd, pg_e2e, tmp_path):
    """Per-test geofabrik sources project with a fresh source + seeded schema."""
    source = "monaco"

    run_cmd("init", "--db", pg_e2e, cwd=tmp_path)
    run_cmd("add", source, cwd=tmp_path)
    run_cmd("sync", "--verbose", cwd=tmp_path)

    yield {"project": tmp_path, "db_url": pg_e2e, "source": source}

    run_cmd("remove", "--force", "monaco", cwd=tmp_path)


# ---------------------------------------------------------------------------
# 5.3 — remove --force removes entry from osmprj.toml
# ---------------------------------------------------------------------------


def test_remove_force_removes_from_toml(isolated_project, run_cmd):
    project = isolated_project["project"]
    run_cmd("remove", "--force", SOURCE_NAME, cwd=project)
    config = tomllib.loads((project / "osmprj.toml").read_text())
    assert SOURCE_NAME not in config.get("sources", {})


# ---------------------------------------------------------------------------
# 5.4 — remove --force removes entry from osmprj.lock
# ---------------------------------------------------------------------------


def test_remove_force_removes_from_lock(isolated_project, run_cmd):
    project = isolated_project["project"]
    # Manually write a lock entry so we can assert it's removed.
    lock_text = (
        "# osmprj.lock — generated by osmprj sync, do not edit\n\n"
        "[sources]\n\n"
        f"[sources.{SOURCE_NAME}]\n"
        'url = "https://example.com/region.osm.pbf"\n'
        'md5 = "abc123"\n'
        'downloaded_at = "2026-01-01T00:00:00+00:00"\n'
    )
    (project / "osmprj.lock").write_text(lock_text)
    run_cmd("remove", "--force", SOURCE_NAME, cwd=project)
    lock = tomllib.loads((project / "osmprj.lock").read_text())
    assert SOURCE_NAME not in lock.get("sources", {})


# ---------------------------------------------------------------------------
# 5.5 — remove --force drops the PostgreSQL schema
# ---------------------------------------------------------------------------


def test_remove_force_drops_schema(isolated_project, run_cmd):
    project = isolated_project["project"]
    db_url = isolated_project["db_url"]
    assert _schema_exists(db_url, SCHEMA_NAME), "Precondition: schema must exist before remove"
    run_cmd("remove", "--force", SOURCE_NAME, cwd=project)
    assert not _schema_exists(db_url, SCHEMA_NAME), (
        f"Schema '{SCHEMA_NAME}' still exists after remove"
    )


# ---------------------------------------------------------------------------
# 5.6 — remove --dry-run leaves everything unchanged
# ---------------------------------------------------------------------------


def test_dry_run_leaves_toml_unchanged(geofabrik_project, run_cmd):
    project = geofabrik_project["project"]
    source = geofabrik_project["source"]
    original = (project / "osmprj.toml").read_text()
    run_cmd("remove", "--dry-run", source, cwd=project)
    assert (project / "osmprj.toml").read_text() == original


def test_dry_run_leaves_lock_unchanged(geofabrik_project, run_cmd):
    project = geofabrik_project["project"]
    source = geofabrik_project["source"]
    original = (project / "osmprj.lock").read_text()
    run_cmd("remove", "--dry-run", source, cwd=project)
    assert (project / "osmprj.lock").read_text() == original


def test_dry_run_leaves_schema_intact(geofabrik_project, run_cmd):
    project = geofabrik_project["project"]
    db_url = geofabrik_project["db_url"]
    source = geofabrik_project["source"]
    run_cmd("remove", "--dry-run", source, cwd=project)
    assert _schema_exists(db_url, source), f"Schema '{source}' was dropped by dry-run"


# ---------------------------------------------------------------------------
# 5.7 — unknown source exits non-zero without modifying anything
# ---------------------------------------------------------------------------


def test_unknown_source_exits_nonzero(isolated_project, run_cmd):
    project = isolated_project["project"]
    result = run_cmd("remove", "nonexistent", cwd=project, check=False)
    assert result.returncode != 0


def test_unknown_source_error_mentions_name(isolated_project, run_cmd):
    project = isolated_project["project"]
    result = run_cmd("remove", "nonexistent", cwd=project, check=False)
    assert "nonexistent" in result.stderr


def test_unknown_source_leaves_toml_unchanged(isolated_project, run_cmd):
    project = isolated_project["project"]
    original = (project / "osmprj.toml").read_text()
    run_cmd("remove", "nonexistent", cwd=project, check=False)
    assert (project / "osmprj.toml").read_text() == original


# ---------------------------------------------------------------------------
# 5.8 — prompt without --force: declining aborts cleanly
# ---------------------------------------------------------------------------


def test_prompt_shown_without_force(isolated_project, binary):
    """Sending newline (default 'N') to stdin should abort without changes."""
    project = isolated_project["project"]
    original_toml = (project / "osmprj.toml").read_text()

    result = subprocess.run(
        [str(binary), "remove", SOURCE_NAME],
        cwd=project,
        input="\n",
        capture_output=True,
        text=True,
        check=False,
    )
    # Should exit cleanly (code 0 — user declined, not an error).
    assert result.returncode == 0
    assert "Aborted" in result.stdout or "aborted" in result.stdout.lower()
    # osmprj.toml must be unchanged.
    assert (project / "osmprj.toml").read_text() == original_toml


def test_prompt_confirms_with_y(isolated_project, binary):
    """Sending 'y' to stdin should proceed and remove the source."""
    project = isolated_project["project"]
    db_url = isolated_project["db_url"]

    result = subprocess.run(
        [str(binary), "remove", SOURCE_NAME],
        cwd=project,
        input="y\n",
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0
    config = tomllib.loads((project / "osmprj.toml").read_text())
    assert SOURCE_NAME not in config.get("sources", {})
    assert not _schema_exists(db_url, SCHEMA_NAME)
