use crate::error::OsmprjError;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use toml_edit::{value, DocumentMut, Item, Table};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceLockEntry {
    pub url: String,
    pub md5: String,
    pub downloaded_at: DateTime<Utc>,
}

/// Serde-compatible mirror for deserialization from TOML.
#[derive(Debug, Default, Deserialize)]
struct LockFileData {
    #[serde(default)]
    sources: HashMap<String, SourceLockEntry>,
}

#[derive(Debug, Default)]
pub struct LockFile {
    pub sources: HashMap<String, SourceLockEntry>,
}

impl LockFile {
    pub fn load() -> Result<Self, OsmprjError> {
        let content = match fs::read_to_string("osmprj.lock") {
            Ok(c) => c,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(e) => {
                return Err(OsmprjError::LockReadFailed {
                    message: e.to_string(),
                })
            }
        };

        let data: LockFileData =
            toml::from_str(&content).map_err(|e| OsmprjError::LockReadFailed {
                message: e.to_string(),
            })?;

        Ok(Self {
            sources: data.sources,
        })
    }

    pub fn save(&self) -> Result<(), OsmprjError> {
        let mut doc = DocumentMut::new();

        if !self.sources.is_empty() {
            let mut sources_table = Table::new();
            for (name, entry) in &self.sources {
                let mut t = Table::new();
                t.insert("url", value(entry.url.as_str()));
                t.insert("md5", value(entry.md5.as_str()));
                t.insert("downloaded_at", value(entry.downloaded_at.to_rfc3339()));
                sources_table.insert(name, Item::Table(t));
            }
            doc.insert("sources", Item::Table(sources_table));
        }

        let header = "# osmprj.lock — generated by osmprj sync, do not edit\n\n";
        let content = format!("{header}{doc}");
        fs::write("osmprj.lock", content).map_err(|e| OsmprjError::LockWriteFailed {
            message: e.to_string(),
        })
    }

    pub fn set_source(&mut self, name: String, entry: SourceLockEntry) -> Result<(), OsmprjError> {
        self.sources.insert(name, entry);
        self.save()
    }

    pub fn remove_source(&mut self, name: &str) -> Result<(), OsmprjError> {
        self.sources.remove(name);
        self.save()
    }
}
